# Generated by Django 4.1.1 on 2022-10-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adwmi', '0002_fronttext_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fronttext',
            name='active',
        ),
    ]
