# Generated by Django 4.1.1 on 2022-10-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwmi', '0003_remove_fronttext_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fronttext',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
