# Generated by Django 4.1.1 on 2022-10-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwmi', '0004_fronttext_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/back')),
            ],
        ),
    ]
