# Generated by Django 4.1.1 on 2022-10-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwmi', '0008_sermon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='placeholder_image',
            field=models.ImageField(upload_to='img/sermons'),
        ),
    ]
