# Generated by Django 4.1.1 on 2022-10-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adwmi', '0010_news_alter_sermon_facebook_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='is_headline',
            new_name='isheadline',
        ),
    ]
