# Generated by Django 4.1.1 on 2022-10-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwmi', '0011_rename_is_headline_news_isheadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_header', models.CharField(default='Annointed Divine Word Ministries International', max_length=100)),
                ('sub_header', models.CharField(default='Where Ministers Are Made', max_length=100)),
                ('text_before_bullets', models.CharField(max_length=500)),
                ('text_bullets', models.CharField(max_length=1000)),
                ('text_after_bullets', models.CharField(max_length=500)),
                ('vision', models.CharField(max_length=300)),
                ('mission', models.CharField(max_length=300)),
                ('core_values', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('is_drop', models.BooleanField(default=False)),
                ('drop_list', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('story', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('number', models.CharField(blank=True, max_length=200)),
                ('birth_date', models.DateField(blank=True)),
                ('role', models.CharField(default='member', max_length=200)),
                ('image_url', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('display_image', models.ImageField(upload_to='img/projects')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_image', models.ImageField(upload_to='img/teams')),
                ('team_name', models.CharField(max_length=100)),
                ('team_slogan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=100)),
                ('hourly_range', models.CharField(max_length=30)),
                ('header', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('event_image', models.ImageField(upload_to='img/events')),
                ('contact_person', models.CharField(max_length=100)),
            ],
        ),
    ]
