# Generated by Django 4.1.1 on 2022-11-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwmi', '0012_about_menuitem_person_project_teams_wschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='fronttext',
            name='big_caption',
            field=models.CharField(default='', max_length=200),
        ),
    ]
