# Generated by Django 4.1.1 on 2022-11-23 02:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adwmi', '0013_fronttext_big_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='fronttext',
            name='back_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='videos/carousel/'),
            preserve_default=False,
        ),
    ]
