# Generated by Django 4.1.1 on 2022-11-25 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adwmi', '0014_fronttext_back_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wschedule',
            old_name='day_of_week',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='person',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='wschedule',
            name='header',
        ),
        migrations.RemoveField(
            model_name='wschedule',
            name='hourly_range',
        ),
        migrations.AddField(
            model_name='person',
            name='full_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/full/persons'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/persons'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(default='Brethren', max_length=200),
        ),
        migrations.AddField(
            model_name='wschedule',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wschedule',
            name='event_video',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='wschedule',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
