# Generated by Django 4.1.1 on 2023-01-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwmi', '0015_rename_day_of_week_wschedule_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fronttext',
            name='big_caption',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='fronttext',
            name='caption',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='fronttext',
            name='header',
            field=models.CharField(max_length=1000),
        ),
    ]
