# Generated by Django 4.1.1 on 2023-01-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwmi', '0016_alter_fronttext_big_caption_alter_fronttext_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_image', models.ImageField(upload_to='img/welcome')),
                ('header', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=500)),
            ],
        ),
    ]
