# Generated by Django 4.1.1 on 2023-01-17 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adwmi', '0017_welcomenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
