# Generated by Django 4.1.1 on 2023-01-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwmi', '0018_sermon_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='core_values',
            field=models.CharField(default='Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi', max_length=300),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission',
            field=models.CharField(default='Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi', max_length=300),
        ),
        migrations.AlterField(
            model_name='about',
            name='sub_header',
            field=models.CharField(default='A Place Where Ministers Are Made', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='text_after_bullets',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='text_bullets',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision',
            field=models.CharField(default='Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi', max_length=300),
        ),
    ]
