# Generated by Django 4.1.1 on 2023-01-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwmi', '0019_alter_about_core_values_alter_about_mission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/teams'),
        ),
    ]
