# Generated by Django 4.1.1 on 2022-10-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DivineSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('story', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('role', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
    ]
