# Generated by Django 4.1.1 on 2022-10-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DivineSite', '0003_news_sermon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=100)),
                ('btn_text', models.CharField(max_length=20)),
                ('is_event', models.BooleanField()),
                ('background_video', models.URLField()),
            ],
        ),
    ]
