# Generated by Django 4.1.1 on 2022-10-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DivineSite', '0004_fronttext'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('activated', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fronttext',
            name='background_video',
        ),
        migrations.AddField(
            model_name='fronttext',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fronttext',
            name='caption',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fronttext',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
    ]
