# Generated by Django 4.1.1 on 2022-10-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DivineSite', '0005_backgroundvideo_remove_fronttext_background_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(default='member', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='story',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
