# Generated by Django 4.1.1 on 2022-10-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DivineSite', '0006_alter_person_birth_date_alter_person_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontText',
        ),
    ]
