# Generated by Django 4.1.1 on 2022-10-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DivineSite', '0007_delete_fronttext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundVideo',
        ),
    ]
