# Generated by Django 4.1.1 on 2022-10-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DivineSite', '0008_delete_backgroundvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sermon',
        ),
    ]
