# Generated by Django 4.1.1 on 2022-10-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DivineSite', '0009_delete_sermon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
